steps:
  - name: ":cookie: Test and Snapshot"
    command:
      - "install_local_deps.sh"
      - "detox build --configuration ios.sim.debug"
      - "detox test --configuration ios.sim.debug"
    artifact_paths: "screenshots/*"